version: '3'
services:
  app:
    image: jmandoo/guacamole:latest
    restart: always
    network_mode: "host"
    #ports:
    #  - '8080:8080'
    container_name: guac
    environment:
      - EXTENSIONS=
      - TZ=America/Chicago
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /root/docker/guac/guacamole:/config
